certData:
  org: "SkasselOrg"
  orgUnit: "RootUnit"
  country: DE
  province: MV
  locality: Rostock
  domain: skassel.net
  issuer: skassel
role: SkasselCertification
certPath: /var/lib/vault/certs/
rootCert:
  name: skassel-root
  passPhrase: ""
intermediate:
  name: skassel-intermediate-root
  passPhrase: ""
